import Foundation

public enum AppLanguage: String, CaseIterable {
    case chinese = "zh-Hans"
    case english = "en"
    public static func resolve(saved: String?, preferred: [String]) -> AppLanguage {
        if let saved, let language = AppLanguage(rawValue: saved) { return language }
        return preferred.first?.hasPrefix("zh") == true ? .chinese : .english
    }
    public static var current: AppLanguage {
        resolve(saved: UserDefaults.standard.string(forKey: "appLanguage"), preferred: Locale.preferredLanguages)
    }
    public var locale: Locale { Locale(identifier: rawValue) }
    public func text(_ chinese: String, _ english: String) -> String { self == .chinese ? chinese : english }
    // Stored titles and errors retain their original identity; translate only when rendering.
    public func display(_ value: String) -> String {
        guard self == .english else { return value }
        if let exact = Self.catalog[value] { return exact }
        let pattern = "([0-9]+) (小时|分钟)额度"
        if let regex = try? NSRegularExpression(pattern: pattern),
           let match = regex.firstMatch(in: value, range: NSRange(value.startIndex..., in: value)),
           match.range.length == (value as NSString).length {
            let source = value as NSString
            return "\(source.substring(with: match.range(at: 1)))-\(source.substring(with: match.range(at: 2)) == "小时" ? "hour" : "minute") quota"
        }
        return value
    }
    public static let catalog: [String: String] = [
        " · 24h估算": " · 24h estimate",
        " · 提前耗尽": " · runs out early",
        " 个百分点": " percentage points",
        " 分钟": " min",
        " 均速估算": " within the last 24h",
        " 天": " days",
        " 小时": " hours",
        " 点": " pp",
        "24h 用量 ": "24h used ",
        "24h 用量 · 积累中": "24h used · collecting",
        "5 小时额度": "5-hour quota",
        "AI Quota 额度详情": "AI Quota Details",
        "Claude 尚未提供订阅额度，请检查账号与订阅": "Claude has not provided subscription quota. Check your account and subscription.",
        "Claude 工作区": "Claude workspace",
        "Claude 工作区：": "Claude workspace: ",
        "Claude 拒绝读取，请打开官方用量页检查": "Claude denied access. Check the official usage page.",
        "Claude 暂时限制刷新频率，请稍后重试": "Claude is rate limiting requests. Try again later.",
        "Claude 未返回用量数据": "Claude returned no usage data.",
        "Claude 用量格式发生变化，请稍后重试": "Claude usage format has changed. Please retry later.",
        "Claude 用量请求失败，请稍后刷新": "Claude usage request failed. Refresh later.",
        "Claude 用量读取失败，请稍后重试": "Cannot read Claude usage. Try again later.",
        "Claude 登录已失效，请重新连接": "Claude sign-in expired. Reconnect your account.",
        "Claude 网络连接失败，请稍后刷新": "Claude network connection failed. Refresh later.",
        "Claude 返回了无法识别的响应": "Claude returned an unrecognized response.",
        "Claude 返回无效用量": "Claude returned invalid usage.",
        "Claude 重置时间无法识别": "Unrecognized Claude reset time.",
        "Claude 页面已暂停，请重新刷新": "Claude page was suspended. Refresh again.",
        "Claude 页面连接超时，请打开官方页面后重试": "Claude page connection timed out. Open the official page and retry.",
        "Claude 页面需要验证或拒绝读取，请打开官方用量页检查": "Claude requires verification or denied access. Check the official usage page.",
        "Codex 无法读取额度，请检查账号登录后重试": "Cannot read Codex quota. Check your sign-in and retry.",
        "Codex 服务已断开": "Codex service disconnected.",
        "Codex 服务未连接": "Codex service is not connected.",
        "Codex 未返回可用额度，请检查登录状态": "Codex returned no quota. Check your sign-in.",
        "Codex 请求超时，请重试": "Codex request timed out. Please retry.",
        "Cursor 拒绝读取，请打开官方用量页检查": "Cursor denied access. Check the official usage page.",
        "Cursor 暂时限制刷新频率，请稍后重试": "Cursor is rate limiting requests. Try again later.",
        "Cursor 未返回两类完整额度，请稍后刷新": "Cursor did not return both quota pools. Refresh later.",
        "Cursor 未返回用量数据": "Cursor returned no usage data.",
        "Cursor 用量格式已变化，请打开官方页面检查": "Cursor usage format has changed. Check the official page.",
        "Cursor 用量请求失败，请稍后刷新": "Cursor usage request failed. Refresh later.",
        "Cursor 用量读取失败，请稍后重试": "Cannot read Cursor usage. Try again later.",
        "Cursor 登录已失效，请重新连接": "Cursor sign-in expired. Reconnect your account.",
        "Cursor 网络连接失败，请稍后刷新": "Cursor network connection failed. Refresh later.",
        "Cursor 返回了无法识别的响应": "Cursor returned an unrecognized response.",
        "Cursor 页面尚未提供完整额度，请稍后刷新": "Cursor has not provided complete quotas. Refresh later.",
        "Cursor 页面已暂停，请重新刷新": "Cursor page was suspended. Refresh again.",
        "Cursor 页面连接超时，请打开官方页面后重试": "Cursor page connection timed out. Open the official page and retry.",
        "Gemini 尚未提供订阅额度，请打开官方用量页检查": "Gemini has not provided subscription quota. Check the official usage page.",
        "Gemini 拒绝读取，请打开官方用量页检查": "Gemini denied access. Check the official usage page.",
        "Gemini 暂时限制刷新频率，请稍后重试": "Gemini is rate limiting requests. Try again later.",
        "Gemini 未返回用量数据": "Gemini returned no usage data.",
        "Gemini 用量格式已变化": "Gemini usage format has changed.",
        "Gemini 用量请求失败，请稍后刷新": "Gemini usage request failed. Refresh later.",
        "Gemini 用量读取失败，请稍后重试": "Cannot read Gemini usage. Try again later.",
        "Gemini 用量页未返回新数据，请连接账号或稍后刷新": "Gemini returned no fresh usage data. Connect your account or refresh later.",
        "Gemini 登录已失效，请重新连接": "Gemini sign-in expired. Reconnect your account.",
        "Gemini 网络连接失败，请稍后刷新": "Gemini network connection failed. Refresh later.",
        "Gemini 返回了无法识别的响应": "Gemini returned an unrecognized response.",
        "Gemini 返回无效或重复额度": "Gemini returned invalid or duplicate quotas.",
        "Gemini 重置时间无法识别": "Unrecognized Gemini reset time.",
        "Gemini 页面已暂停，请重新刷新": "Gemini page was suspended. Refresh again.",
        "Gemini 页面连接超时，请打开官方页面后重试": "Gemini page connection timed out. Open the official page and retry.",
        "Handpan 合奏": "Handpan Ensemble",
        "Opus 每周": "Opus weekly",
        "Sonnet 每周": "Sonnet weekly",
        "。变化百分号表示额度百分点，例如66%到63%显示↓3%。": ". Changes are percentage points: 66% to 63% is shown as ↓3%.",
        "。实线为历史，虚线为预测；重置与缺口不连线。": ". Solid: history. Dashed: forecast. Resets and gaps are not connected.",
        "上移 ": "Move Up ",
        "下移 ": "Move Down ",
        "主要额度": "Primary quota",
        "保持置顶": "Keep on Top",
        "停止密切关注": "Stop Close Monitoring",
        "全部提供商立即刷新，此后每 10 秒刷新；再次点击停止。时长在更多菜单设置。": "Refresh all providers now, then every 10 seconds. Click again to stop. Set duration in More.",
        "关注 ": "Watch ",
        "刚刚": "just now",
        "刷新": "Refresh",
        "剩余额度": "Remaining",
        "剩余额度 · CX: 5h = Codex 5 小时 / W = 每周 · CU: C = Cursor Models / O = Other Models · CL: 5h = Claude 5 小时 / W = 每周 · GM: 5h = Gemini 5 小时 / W = 每周 · ! 表示数据过期": "Remaining · CX: Codex 5h / weekly · CU: Cursor Models / Other Models · CL: Claude 5h / weekly · GM: Gemini 5h / weekly · ! means stale data",
        "剩余额度变化（百分点）": "Remaining quota change (percentage points)",
        "历史暂时无法保存，退出后可能丢失本次记录": "Cannot save history. This session’s records may be lost on exit.",
        "历史版本不兼容": "Incompatible history version",
        "取消悬浮窗置顶": "Unpin Floating Window",
        "取消置顶": "Unpin",
        "可用约 ": "Runway ~",
        "后重置": " until reset",
        "周期结束预计剩余 ": "Remaining at reset: ",
        "周期趋势": " cycle trend",
        "完成 Gemini 登录后关闭窗口，再刷新额度": "Finish signing in to Gemini, close the window, then refresh.",
        "完成排序": "Done Reordering",
        "实线 历史 · 虚线 预测": "Solid: history · dashed: forecast",
        "实线为已记录用量；缺失区间留空。需有效周期信息和最新额度才能预测。": "Solid lines show recorded usage; gaps remain blank. Forecasts require valid cycle dates and fresh data.",
        "密切关注": "Close Watch",
        "密切关注中 · 每 10 秒同步": "Monitoring · sync every 10 seconds",
        "密切关注时长 · 下次开启生效": "Monitoring duration · applies next time",
        "展开": "Expand",
        "已展开": "Expanded",
        "已折叠": "Collapsed",
        "已用 % · 周期与近24h历史": "Used % · cycle + last 24h",
        "已用额度趋势，实线为观测历史，虚线为均速预测；缺失历史不补画": " usage trend. Solid: observed history. Dashed: average-rate forecast. Missing history is not filled in.",
        "开启密切关注": "Start Close Monitoring",
        "悬浮窗置顶": "Pin Floating Window",
        "打开 Codex": "Open Codex",
        "折叠": "Collapse",
        "按均速预计已耗尽": "Estimated exhausted at current rate",
        "按本周期累计用量 / 周期已过时间预测": "Based on cycle usage / elapsed cycle time",
        "按近24h已记录 ": "Based on the observed ",
        "收起": "Collapse",
        "效果预览": "Effect preview",
        "数据过期": "Stale data",
        "无法识别 Cursor 额度，保留上次数据": "Unrecognized Cursor quota. Keeping previous data.",
        "旧历史无法读取，原文件已保留；本次历史仅保存在内存": "Cannot read saved history. The original file is preserved; this session’s history is kept in memory only.",
        "显示 / 隐藏悬浮窗": "Show / Hide Floating Window",
        "显示或隐藏桌面悬浮窗": "Show or hide floating window",
        "暂无变化记录": "No changes yet",
        "暂无消耗 · 余量充足": "No usage · ample quota",
        "更多操作": "More",
        "最近变化": "Recent Changes",
        "未找到 Codex，请安装 Codex 或选择程序路径": "Codex not found. Install Codex or choose its executable.",
        "未连接": "Not connected",
        "次要额度": "Secondary quota",
        "正在同步": "Syncing",
        "正在读取额度…": "Loading quota…",
        "正在验证上次数据": "Validating cached data",
        "每分钟同步": "Sync every minute",
        "每周额度": "Weekly quota",
        "深灰蓝：更早已用；雾蓝：本周期近24h已用；鲜艳段：剩余，红黄绿表示能否撑到重置。历史不足时分段仅表示已知部分。": "Dark gray-blue: earlier usage. Mist blue: this cycle’s last 24h usage. Color: remaining quota; green/yellow/red indicates runway until reset. Partial history shows known usage only.",
        "现在": "Now",
        "登录后关闭窗口并刷新额度": "Close this window after signing in, then refresh quota",
        "登录验证": "Sign-in verification",
        "等待重置同步": "Waiting for reset sync",
        "经典钟琴": "Classic Chimes",
        "耗尽": " early",
        "请在 Claude 官方窗口完成登录": "Complete sign-in in the official Claude window.",
        "请在 Claude 登录弹窗完成验证": "Complete verification in the Claude sign-in popup.",
        "请在 Cursor 官方窗口完成登录": "Complete sign-in in the official Cursor window.",
        "请在 Cursor 登录弹窗完成验证": "Complete verification in the Cursor sign-in popup.",
        "请在 Gemini 官方窗口完成登录": "Complete sign-in in the official Gemini window.",
        "请在 Gemini 登录弹窗完成验证": "Complete verification in the Gemini sign-in popup.",
        "请在更多菜单选择 Claude 工作区": "Choose a Claude workspace in More.",
        "调整卡片顺序": "Reorder Cards",
        "账期重置 · ": "Billing reset · ",
        "超过10年": "Over 10 years",
        "过去24小时累计消耗（百分点），可跨重置超过100点。带 * 表示历史不足或存在缺口；记录 ": "Usage over the last 24h in percentage points; may exceed 100 across resets. * means partial history or gaps. Observed: ",
        "连接 ": "Connect ",
        "连接 Claude 账号": "Connect Claude Account",
        "连接 Cursor 账号": "Connect Cursor Account",
        "连接 Gemini 账号": "Connect Gemini Account",
        "连接账号后显示真实余量": "Connect an account to see your quota",
        "退出 AI Quota": "Quit AI Quota",
        "选择 Codex 可执行程序": "Choose Codex Executable",
        "选择 Codex 程序…": "Choose Codex Executable…",
        "选择已安装的 codex 程序。": "Select the installed codex executable.",
        "重置": "Reset",
        "重置时间已到 · 等待同步": "Reset due · waiting for sync",
        "隐藏悬浮窗": "Hide Floating Window",
        "音效（额度变化与关注开关）": "Sounds (quota changes and monitoring)",
        "音色：": "Sound: ",
        "预测暂停 · 等待同步": "Forecast paused · awaiting sync",
        "预测暂缺周期信息": "Cycle dates unavailable",
        "预览 ": "Preview ",
        "预览 · ": "Preview · ",
        "预览：大幅恢复 · +20%": "Preview: Large Recovery · +20%",
        "预览：小幅减少 · −1%": "Preview: Small Decrease · −1%",
        "预览：明显减少 · −3%": "Preview: Notable Decrease · −3%",
        "预计提前 ": "Runs out ",
        "预计耗尽": "Exhaustion",
        "额度": "Quota",
        "额度变化": "Quota change",
        "，每小时约 ": ", approximately "
    ]
}
